# Generated by Django 4.2.7 on 2023-11-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_tomatoes', models.IntegerField(default=0)),
                ('number_of_money', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('number_of_counts', models.IntegerField(default=0)),
            ],
        ),
    ]
